# Cloud Build configuration for backend deployment
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/invoice-platform-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/invoice-platform-backend:latest'
      - '.'
    dir: 'backend'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/invoice-platform-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/invoice-platform-backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'invoice-platform-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/invoice-platform-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=$PROJECT_ID,GCP_REGION=us-central1,STORAGE_BUCKET_NAME=$PROJECT_ID-invoices,ENVIRONMENT=production,LOG_LEVEL=INFO,FIRESTORE_DATABASE=(default),MAX_FILE_SIZE_MB=10,ALLOWED_FILE_TYPES=application/pdf,SIGNED_URL_EXPIRATION_HOURS=1'
      - '--set-secrets'
      - 'FIREBASE_SERVICE_ACCOUNT_SECRET=firebase-service-account:latest'
      - '--service-account'
      - 'invoice-platform-sa@$PROJECT_ID.iam.gserviceaccount.com'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/invoice-platform-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/invoice-platform-backend:latest'

# Build timeout
timeout: '1200s'

# Options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
